import { ArrowRightLeft, LayoutDashboard, LogOut, PlusCircle, Send, User, Users, Wallet } from 'lucide-react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import NotificationBell from '../../features/notifications/components/NotificationBell';
import { useAuthStore } from '../../store/authStore';

export const DashboardLayout = () => {

   const navigate = useNavigate();
  // Extract the logout function from your Zustand store
  const logout = useAuthStore((state) => state.logout);
  const accessToken = useAuthStore((state) => state.accessToken);

  const handleLogout = () => {
    logout(); // This clears the tokens from Zustand and localStorage
    navigate('/login'); // Redirect to login page
  };

  // NEW: Determine if the user is an admin by decoding the JWT payload
  let isAdmin = false;
  if (accessToken) {
    try {
      // A JWT has 3 parts separated by dots: header.payload.signature
      const base64Url = accessToken.split('.')[1];
      const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
      const payload = JSON.parse(window.atob(base64));
      
      // Match the role format generated by your JwtService
      isAdmin = payload.role === 'ROLE_ADMIN';
    } catch (e) {
      console.error("Failed to decode token for role verification", e);
    }
  }
  return (
    <div className="flex h-screen w-full bg-slate-50">
      {/* Sidebar - Fixed width, sticky height */}
      <aside className="w-64 bg-white border-r border-slate-200 flex flex-col shrink-0">
        <div className="p-6 font-bold text-xl text-indigo-600 flex items-center gap-2">
            <Wallet /> CrossPesa
        </div>
        
        <nav className="flex-1 px-4 space-y-2">
            <NavLink to="/dashboard" className="flex items-center gap-3 px-4 py-2 hover:bg-slate-100 rounded-lg">
                <LayoutDashboard size={20}/> Dashboard
            </NavLink>
            <NavLink 
              to="/topup" 
              className={({ isActive }) => `flex items-center gap-3 px-4 py-2 rounded-lg transition-colors ${isActive ? 'bg-indigo-50 text-indigo-700' : 'hover:bg-slate-100 text-slate-700'}`}
            >
                <PlusCircle size={20}/> Top-up Wallet
            </NavLink>
            <NavLink to="/transfer" className="flex items-center gap-3 px-4 py-2 hover:bg-slate-100 rounded-lg">
                <Send size={20}/> Send Money
            </NavLink>
            <NavLink to="/beneficiaries" className="flex items-center gap-3 px-4 py-2 hover:bg-slate-100 rounded-lg">
                <Users size={20}/> Beneficiaries
            </NavLink>
            <NavLink to="/exchange" className="flex items-center gap-3 px-4 py-2 hover:bg-slate-100 rounded-lg">
                <ArrowRightLeft size={20}/> Move Funds
            </NavLink>
            <NavLink to="/wallets" className="flex items-center gap-3 px-4 py-2 hover:bg-slate-100 rounded-lg transition-colors">
              <Wallet size={20} className="text-slate-600" /> 
              <span className="font-medium text-slate-700">New Wallet</span>
            </NavLink>
            <NavLink to="/kyc-submission" className="flex items-center gap-3 px-4 py-2 hover:bg-slate-100 rounded-lg transition-colors">
              <User size={20} className="text-slate-600" /> 
              <span className="font-medium text-slate-700">KYC Submission</span>
            </NavLink>

            {/* NEW: Admin Links wrapped in conditional rendering */}
            {isAdmin && (
              <>
                <div className="pt-4 pb-2">
                    <p className="px-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Admin Controls</p>
                </div>
                <NavLink 
                  to="/admin-dashboard" 
                  className={({ isActive }) => `flex items-center gap-3 px-4 py-2 rounded-lg transition-colors ${isActive ? 'bg-red-50 text-red-700' : 'hover:bg-slate-100 text-slate-700'}`}
                >
                  <LayoutDashboard size={20} /> Platform Ledger
                </NavLink>
                <NavLink 
                  to="/admin-users" 
                  className={({ isActive }) => `flex items-center gap-3 px-4 py-2 rounded-lg transition-colors ${isActive ? 'bg-red-50 text-red-700' : 'hover:bg-slate-100 text-slate-700'}`}
                >
                  <Users size={20} /> Manage Users
                </NavLink>
                <NavLink 
                  to="/admin-kyc" 
                  className={({ isActive }) => `flex items-center gap-3 px-4 py-2 rounded-lg transition-colors ${isActive ? 'bg-red-50 text-red-700' : 'hover:bg-slate-100 text-slate-700'}`}
                >
                  <User size={20} /> Kyc Admin
                </NavLink>
              </>
            )}

            
        </nav>
      </aside>

      {/* Right Side Content Area - Column Layout */}
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
        {/* Top Navbar */}
        <header className="h-16 bg-white border-b border-slate-200 flex items-center justify-end px-8 shrink-0">
          <div className="flex items-center gap-6">

            {/* The Notification Bell */}
            <NotificationBell />
            
            {/* Optional User Profile Avatar */}
            <div className="flex items-center gap-3 cursor-pointer">
              <div className="h-9 w-9 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center font-bold text-sm">
                EO {/* Initials */}
              </div>
            </div>

            <div className="p-4 border-t border-slate-200">
          <button 
            onClick={handleLogout}
            className="flex items-center w-full gap-3 px-4 py-2 text-red-600 hover:bg-red-50 hover:text-red-700 rounded-lg transition-colors font-medium"
          >
            <LogOut size={20} />
            Logout
          </button>
        </div>
            
          </div>
        </header>
         {/* Outlet acts as the "portal" for child routes */}
      <main className="flex-1 overflow-y-auto p-8">
        <Outlet /> 
      </main>
      </div>
    </div>
  );
};